schema_version = "1.0.0"

id = "stellar_blade_fbx_exporter"
version = "1.1.4"
name = "Stellar Blade FBX Exporter"
tagline = "Import and export FBX files with Stellar Blade bone fixes"
maintainer = "AzurieWolf, Lemi21, Njaecha"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-2.0-or-later",
]
copyright = [
  "2011-2026 Blender Foundation",
]

[permissions]
files = "Import and export FBX files and read bundled skeleton JSON files"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
